name: ci-cd

on:
  push:
    branches: master

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  docker-build-push:
    name: CI-CD
    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cptdoraemon/zdy-website-3:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Configure SSH
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          HOST: prod
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/$HOST.key
          chmod 600 ~/.ssh/$HOST.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/$HOST.key
            StrictHostKeyChecking no
          END

      - name: Change directory
        run: ssh "$HOST" 'cd ~/zdy-website-3-docker'

      - name: Stop
        run: ssh "$HOST" 'sudo docker-compose stop'

      - name: Up
        run: ssh "$HOST" 'sudo docker-compose up'
