name: Build Docker image and push to Docker Hub

on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  docker-build:
    # Name the Job
    name: Build Docker image
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2.2.1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: cptdoraemon/zdy-website-3
          tag_with_ref: true
